### ISSUE TITLE
Permissions errors on trying to move a message

### ISSUE THREAD

**Issue by evantill** [laralove143/discord-interchannel-message-mover#4]
Trying the bot I have this error message : 

```
interchannel message mover
BOT
 — Aujourd’hui à 14:00
please make sure i have these permissions:

view channels
manage webhooks
send messages
manage messages
```

**Comment by laralove143** [comment]
sorry for the late reply, could you show the channel, category and the bot's roles' permissions?

**Comment by evantill** [comment]
Bot rights when adding it to the server :
<img width="440" alt="Autoriser_l_accès_à_ton_compte" src="https://user-images.githubusercontent.com/609288/174014935-6d946814-5b5d-4997-ada5-749a9b12edae.png">

Role permissions:
<img width="432" alt="Sans_titre" src="https://user-images.githubusercontent.com/609288/174016353-c377b79e-257f-42d0-bda2-e228f6da0e60.png">

**Comment by evantill** [comment]
I do no see the  `manage messages` permission as seen in the help message :  
<img width="452" alt="bots_-_Discord" src="https://user-images.githubusercontent.com/609288/174016959-e46a133a-c807-4a98-bb06-26a661479d07.png">

**Comment by evantill** [comment]
Adding the `manage messages` to the bot role permissions solve the error.

**Comment by laralove143** [comment]
apparently i picked manage nicknames instead of manage messages.. thanks for the heads up

**Comment by laralove143** [comment]
feel free to reopen if the issue is still there
