### ISSUE TITLE
documentation: warn user about limitation

### ISSUE THREAD

**Issue by evantill** [laralove143/discord-interchannel-message-mover#5]
I have installed the bot to clean some channels. But after trying to move messages, I realized that the bot can only move messages after it has joined the server.

What about adding a warning about that limitation in the bot documentation ?

**Comment by evantill** [comment]
Will it be possible to remove this limitation in the future ? Or is it "by design" ?

**Comment by laralove143** [comment]
sadly it's a discord limitation:
https://discord.com/developers/docs/resources/channel#bulk-delete-messages
> This endpoint will not delete messages older than 2 weeks, and will fail with a 400 BAD REQUEST if any message provided is older than that or if any duplicate message IDs are provided.

i could add it to the readme though

**Comment by laralove143** [comment]
feel free to reopen for further questions
